#ifndef IDT_H
#define IDT_H

#include "libc/stdint.h"

// IDT entry structure
typedef struct {
  uint16_t offset_low;
  uint16_t selector;
  uint8_t zero;
  uint8_t type_attr;
  uint16_t offset_high;
} __attribute__((packed)) idt_entry_t;

// IDT pointer structure
typedef struct {
  uint16_t limit;
  uint32_t base;
} __attribute__((packed)) idt_ptr_t;

#define IDT_ENTRIES 256
extern idt_entry_t idt[IDT_ENTRIES];
extern idt_ptr_t idt_ptr;


// Interrupt Request Numbers (IRQs) definitions generated by Claude:
#define IRQ0 32
#define IRQ1 33
#define IRQ2 34
#define IRQ3 35
#define IRQ4 36
#define IRQ5 37
#define IRQ6 38
#define IRQ7 39
#define IRQ8 40
#define IRQ9 41
#define IRQ10 42
#define IRQ11 43
#define IRQ12 44
#define IRQ13 45
#define IRQ14 46
#define IRQ15 47

// Function declarations
void set_idt_entry(int n, uint32_t handler);
void load_idt();

#endif