// Lookup table for scancode to ASCII conversion was generated by Claude

#ifndef KEYBOARD_H
#define KEYBOARD_H

#define SCANCODE_MAX 0x58

/**
 * @brief Function pointer type for keyboard callback functions.
 * @param ch The character that was pressed.
 */
typedef void (*keyboard_callback_t)(char ch);

/**
 * @brief Initialize the keyboard input system.
 * This function sets up the necessary structures and configurations for
 * keyboard input.
 */
void input_init();

/**
 * @brief Set the keyboard subscriber callback function.
 * @param callback The function to be called when a key is pressed.
 */
void input_set_keyboard_subscriber(keyboard_callback_t callback);

/**
 * @brief Route a keystroke to the current keyboard subscriber.
 * @param ch The character to be sent to the subscriber.
 */
void input_route_keystroke(char ch);

/**
 * @brief Convert a scancode to its corresponding ASCII character.
 * @param scancode The scancode to be converted.
 * @return The corresponding ASCII character, or 0 if the scancode is invalid.
 */

static const char scancode_to_ascii[SCANCODE_MAX] = {
    0,    // 0x00 - Empty
    0x1B, // 0x01 - ESC
    '1',  '2', '3', '4', '5', '6', '7', '8', '9', '0', '-',  '=',
    0x08, // 0x0E - Backspace
    '\t', // 0x0F - Tab
    'q',  'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '[',  ']',
    '\n', // 0x1C - Enter
    0,    // 0x1D - Left Control
    'a',  's', 'd', 'f', 'g', 'h', 'j', 'k', 'l', ';', '\'', '`',
    0, // 0x2A - Left Shift
    '\\', 'z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/',
    0,                                               // 0x36 - Right Shift
    '*',                                             // 0x37 - Keypad *
    0,                                               // 0x38 - Left Alt
    ' ',                                             // 0x39 - Space
    0,                                               // 0x3A - CapsLock
    0,    0,   0,   0,   0,   0,   0,   0,   0,   0, // 0x3B-0x44 - F1-F10
    0,                                               // 0x45 - NumLock
    0,                                               // 0x46 - ScrollLock
    '7',  '8', '9', '-', '4', '5', '6', '+', '1', '2', '3',  '0', '.'};

#endif