// Generated by DeepSeek for debug purposes. Fix before delivering.

#include "libc/stdint.h"
#include "system.h"

void init_ps2() {
  // Disable both PS/2 ports (keyboard + mouse)
  outb(0x64, 0xAD); // Disable first port (keyboard)
  outb(0x64, 0xA7); // Disable second port (mouse)

  // Flush any pending data
  while (inb(0x64) & 0x01) {
    inb(0x60); // Read and discard
  }

  // Configure PS/2 controller (enable keyboard interrupt)
  outb(0x64, 0x20); // Read controller config byte
  uint8_t config = inb(0x60);
  config |= 0x01;   // Enable keyboard interrupt (IRQ1)
  config &= ~0x02;  // Disable mouse interrupt (IRQ12)
  outb(0x64, 0x60); // Write back config
  outb(0x60, config);

  // Enable keyboard port
  outb(0x64, 0xAE);
}

void init_keyboard() {
  // Wait until input buffer is empty
  int timeout = 100000;
  while ((inb(0x64) & 0x02) && timeout-- > 0)
    ;

  // Send "Enable Scanning" command (0xF4)
  outb(0x60, 0xF4);

  // Wait for ACK (0xFA)
  timeout = 100000;
  while (!(inb(0x64) & 0x01) && timeout-- > 0)
    ;
  if (inb(0x60) != 0xFA) {
    // Handle error: Keyboard didn't acknowledge
  }
}