// Code generated by Claude for debug purposes, fix it before delivery.
#include "keyboard.h"
#include "print.h"
#include "system.h"

void init_ps2() {
  // Wait for keyboard controller to be ready
  while ((inb(0x64) & 2) != 0) {
    io_wait();
  }

  // Disable devices
  outb(0x64, 0xAD); // Disable first PS/2 port
  io_wait();

  // Flush output buffer
  while ((inb(0x64) & 1) != 0) {
    inb(0x60);
    io_wait();
  }

  // Configure controller - enable IRQ1
  outb(0x64, 0x20); // Read configuration byte
  io_wait();
  uint8_t config = inb(0x60);
  config |= 1;         // Enable keyboard interrupt
  config &= ~(1 << 6); // Enable translation to scan code set 1

  outb(0x64, 0x60); // Write configuration byte
  io_wait();
  outb(0x60, config);
  io_wait();

  // Re-enable first PS/2 port
  outb(0x64, 0xAE);
  io_wait();

  // Reset keyboard and wait for acknowledgment
  outb(0x60, 0xFF);
  io_wait();
  io_wait();

  // Wait for and discard the self-test response
  if (inb(0x60) != 0xFA) {
    // Continue anyway - some keyboards don't ACK properly
  }

  // Drain any pending data
  while ((inb(0x64) & 1) != 0) {
    inb(0x60);
    io_wait();
  }

  // Enable scanning
  outb(0x60, 0xF4);
  io_wait();
  io_wait();

  // We're done - don't wait for ACK as some keyboards behave differently
}