// Code generated by Claude for debug purposes, fix it before delivery.
#include "keyboard.h"
#include "print.h"
#include "system.h"

void init_ps2() {
  // Disable keyboard and mouse interrupts
  outb(0x64, 0xAD); // Disable first PS/2 port
  outb(0x64, 0xA7); // Disable second PS/2 port

  // Flush output buffer
  io_wait();
  while ((inb(0x64) & 1) != 0) {
    inb(0x60);
    io_wait();
  }

  // Set controller configuration
  outb(0x64, 0x20); // Command: Read configuration
  io_wait();
  uint8_t config = inb(0x60);
  config |= 1;      // Enable keyboard interrupt
  outb(0x64, 0x60); // Command: Write configuration
  io_wait();
  outb(0x60, config);
  io_wait();

  // Re-enable devices
  outb(0x64, 0xAE); // Enable first PS/2 port
  io_wait();

  // Reset keyboard
  outb(0x60, 0xFF);
  io_wait();

  // Wait for ACK (0xFA)
  if (inb(0x60) != 0xFA) {
    print("Keyboard reset failed!\n");
  }

  // Set scan code set
  outb(0x60, 0xF0); // Command: Set scan code set
  io_wait();
  if (inb(0x60) != 0xFA) {
    print("Keyboard command failed!\n");
  }

  outb(0x60, 0x02); // Use scan code set 2
  io_wait();
  if (inb(0x60) != 0xFA) {
    print("Keyboard command failed!\n");
  }

  // Enable scanning
  outb(0x60, 0xF4);
  io_wait();
  if (inb(0x60) != 0xFA) {
    print("Keyboard enable failed!\n");
  }
}